spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/memento

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/memento
          jwk-set-uri: http://localhost:8181/realms/memento/protocol/openid-connect/certs

server:
    port: 8081

logging:
  level:
    org.springframework.security: DEBUG
    org.keycloak: INFO